### ISSUE TITLE
Add ssh-agent support to k3s-release utility

### ISSUE THREAD

**Issue by nikolaishields** [rancher/ecm-distro-tools#134]
Presently the k3s-release utility explicitly loads the the ssh credentials from the default location in the filesystem (~/.ssh/.id-rsa)

**Comment by briandowns** [comment]
Is there a benefit to this other than edge case / one off use cases?

**Comment by nikolaishields** [comment]
I believe that there is benefit in not making assumptions on the environment. By making the integration with SSH detect whether an agent is being used or if a default key exists. The alternative route would be to not use SSH at all in favor of token based access to the repository.

**Comment by briandowns** [comment]
We may want to find out who is using anything different than a standard setup.

**Comment by nikolaishields** [comment]
Looks like the vote was split 50-50 via the slack poll. Perhaps we could avoid ssh operations altogether by going the route of HTTPS/ github api token (this should exist within the present context and function within opdom in the future). I'd have to dig a little deeper into the git library, but looks feasible with minimal effort.

**Comment by galal-hussein** [comment]
@nikolaishields Back when we discussed this, we agreed that this is an edge case, and we should make the ecm-distro-tools as generic as possible to avoid edge cases rabbit holes, however you are welcome to try to remove git ssh operations in the modify_script here https://github.com/rancher/ecm-distro-tools/blob/9846028718f19462319f0056b9265b1e624f2139/release/k3s/k3s.go#L45-L67, but I dont think it will be that easy, since you will need to codify both this whole script to git operations via the API which is somehow complicated.

**Comment by briandowns** [comment]
I think we should probably close this for now and address it if it ever becomes a going concern.
