### ISSUE TITLE
gen_release_notes exec version.sh

### ISSUE THREAD

**Issue by brooksn** [rancher/ecm-distro-tools#144]
Investigate if there's a safe way to download and run version.sh scripts from k3s and rke2 projects.

**Comment by briandowns** [comment]
@brooksn Can you provide some more context around this request?

**Comment by brooksn** [comment]
Instead of downloading version.sh and go.mod from github and running grep to parse versions, it could be easier to maintain to download and execute version.sh and print the variables we care about for release notes.

**Comment by Tashima42** [comment]
This is a list of variables that are used on `gen_release_notes` that can or can't be replaced by executing the `version.sh` file from either rke2 or k3s. I have omitted the first few variables because I don't think they apply to the scope of this issue.

I noticed that `CNIPluginsVersion` isn't being used anywhere, so we probably should remove it. 

One possible way to run and parse the variables from `version.sh` is using the `os/exec` library, storing the STDOUT in a buffer and parsing the variables from it, I'm uncertain if this would be better than what we're already doing.

Should I continue this investigation? If yes, does anyone have a better suggestion on how to do this?

| Field                       | used on  | is on version.sh |
|-----------------------------|----------|------------------|
| EtcdVersionRKE2             | rke2     | ✅                |
| EtcdVersionK3S              | k3s      | ❌                |
| ContainerdVersionK3S        | k3s      | ✅                |
| ContainerdVersionGoMod      | rke2     | ❌                |
| ContainerdVersionRKE2       | rke2     | ❌                |
| RuncVersionGoMod            | k3s      | ✅                |
| RuncVersionBuildScript      | k3s      | ✅                |
| RuncVersionRKE2             | rke2     | ❌                |
| CNIPluginsVersion           | N/A      | N/A              |
| MetricsServerVersion        | k3s/rke2 | ❌                |
| TraefikVersion              | k3s      | ❌                |
| CoreDNSVersion              | k3s/rke2 | ❌                |
| IngressNginxVersion         | rke2     | ❌                |
| HelmControllerVersion       | k3s/rke2 | ❌                |
| FlannelVersionRKE2          | rke2     | ❌                |
| FlannelVersionK3S           | k3s      | ✅                |
| CalicoVersion               | rke2     | ❌                |
| CanalCalicoVersion          | rke2     | ❌                |
| CiliumVersion               | rke2     | ❌                |
| MultusVersion               | rke2     | ❌                |
| KineVersion                 | k3s      | ❌                |
| SQLiteVersion               | k3s      | ❌                |
| LocalPathProvisionerVersion | k3s      | ❌                |

**Comment by brooksn** [comment]
I think compiling this table was a great step. My opinion is that proceeding with exec-ing the version.sh script would just create another branch in the code that could be burdensome to maintain.

In my experience maintaining this program, sometimes my pain point is in release/release.go#GenReleaseNotes, where many different grep and parsing techniques are intermingled. For example, `ContainerdVersionK3S`, `ContainerdVersionRKE2`, and `ContainerdVersionGoMod` are defined right next to each other, and then there is conditional logic inside the go templates themselves that determine which versions they should be used for. Maybe there's some refactoring here (maybe better isolating k3s/rke2 specific paths, and cleaning up the templates themselves) that could make maintenance easier.

**Comment by Tashima42** [comment]
I agree, to me, executing `version.sh` is just creating more code to maintain, since we wouldn't be able to replace any of the existing approaches to get the versions, just add a new one. Refactoring and cleaning the code looks like a simpler and faster approach, I could do this in the next sprint to address some pain points you mentioned. 

- [ ] Remove unused code
- [ ] Better separate rke2 and k3s instead of getting all field always.
- [ ] Move the logic out of the templates

**Comment by brooksn** [comment]
The markdown table whitespaces have bothered me for a while, so maybe refactoring that as well:

```go
package main

import (
	"fmt"
	"strings"
)

type Component struct {
	Name    string
	Version string
}

func (c *Component) url() string {
	switch c.Name {
	default:
		return "https://example.com"
	}
}

type Components []Component

func (components *Components) maxWidth() (int, int, int) {
	nameMax, versionMax, urlMax := 0, 0, 0
	for _, component := range *components {
		if len(component.Name) > nameMax {
			nameMax = len(component.Name)
		}
		if len(component.Version) > versionMax {
			versionMax = len(component.Version)
		}
		url := component.url()
		if len(url) > urlMax {
			urlMax = len(url)
		}
	}
	return nameMax, versionMax, urlMax
}

func (components *Components) Markdown() string {
	var sb strings.Builder

	nameMax, versionMax, urlMax := components.maxWidth()

	header := fmt.Sprintf("| %-*s | %-*s | %-*s |\n", nameMax, "Name", versionMax, "Version", urlMax, "URL")
	sb.WriteString(header)

	separator := fmt.Sprintf("| %s | %s | %s |\n", strings.Repeat("-", nameMax), strings.Repeat("-", versionMax), strings.Repeat("-", urlMax))
	sb.WriteString(separator)

	for _, component := range *components {
		row := fmt.Sprintf("| %-*s | %-*s | %-*s |\n", nameMax, component.Name, versionMax, component.Version, urlMax, component.url())
		sb.WriteString(row)
	}

	return sb.String()
}

func main() {
	components := Components{
		{"Etcd", "v3.5.7-k3s1"},
		{"Containerd", "v1.6.19-k3s1"},
		{"Runc", "v1.1.5"},
	}
	fmt.Println(components.Markdown())
	/**
	| Name       | Version      | URL                 |
	| ---------- | ------------ | ------------------- |
	| Etcd       | v3.5.7-k3s1  | https://example.com |
	| Containerd | v1.6.19-k3s1 | https://example.com |
	| Runc       | v1.1.5       | https://example.com |
	*/
}

```

**Comment by Tashima42** [comment]
I noticed that the Flannel tag linked in the rke2 release notes is broken, I don't know for how long, but it is in the [last release](https://github.com/rancher/rke2/releases/tag/v1.27.2%2Brke2r1)

@brooksn @briandowns The last tag for the [k3s-io flannel fork](https://github.com/k3s-io/flannel/tags) is from 2020, are we still using it for rke2?
