### ISSUE TITLE
release_k3s modify_k3s should sign off commits

### ISSUE THREAD

**Issue by brooksn** [rancher/ecm-distro-tools#177]
Commits created by the modify_k3s subcommand should always include a signed-off message in the commit.

**Comment by Tashima42** [comment]
I think it this was already added in this [commit](https://github.com/rancher/ecm-distro-tools/commit/306605f50d5d97fd3c886b92a853f0d0697b6eac#diff-9e4900fdb68c9c954cd9d4413f9ff22b8708544a866e80b77e7448b0ae9d6babR65), but I'm not certain, since there are some commits that look like they were created by this script, but doesn't include `Signed-off-by`

**Comment by Tashima42** [comment]
This is an example of a commit that I think was created using this script: https://github.com/k3s-io/k3s/pull/7575/commits/db643c5590181492c84b8f130f16345134b7e15f
