### ISSUE TITLE
Ability to set dev or production branches for KDM references

### ISSUE THREAD

**Issue by deniseschannon** [rancher/ecm-distro-tools#253]
Manual process today right before and after the release:

Create a PR that moves from development branches to production branches for kontainer-driver-metadata (KDM). 

**Update variables in settings/settings.go** 
- [KDMBranch](https://github.com/rancher/rancher/blob/release/v2.8/pkg/settings/setting.go#L84) - Branch where KDM is pointed to            

**Update arguments in package/Dockerfile** 
- [CATTLE_KDM_BRANCH](https://github.com/rancher/rancher/blob/release/v2.8/package/Dockerfile#L24) - Branch where KDM is pointed to

**Update the environment variable in Dockerfile.dapper**
- [CATTLE_KDM_BRANCH](https://github.com/rancher/rancher/blob/release/v2.8/Dockerfile.dapper#L16) - Branch where KDM is pointed to and this is used for CI to download files

**Comment by jiaqiluo** [comment]
> Update the command to identify the directory and current branch instead of using flags.
> 
> The user will go to the local rancher repo, switch to the base branch and will not need to set the current set kdm branch, the command needs to automatically identify these infos.
> 
> ```shell
> rancher_release-darwin-arm64 set-kdm-branch-refs --new-kdm-branch DEMO --create-pr
> ```


Additional:
1. The command should print out the current value it detects and the new value to be applied; it will be more convenient to print out the filenames after changes are done.
3. Operators usually make changes and submit PR from a dedicated branch instead of the default `release-v2.7/v2.8`, so when `create-pr` is set, it should create & make PR from a new branch automatically in the background.
